[package]
name = "tasks"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1"
log = "0.4"
simplelog = "0.12"
once_cell = "1.13"